// Schema DDL, generated for the active SQL dialect ('sqlite' | 'pg').
// Money/aggregate columns are doubles (exact for integer GMV up to 2^53);
// counts are integers/bigints. Both dialects support IF NOT EXISTS + ON CONFLICT.

export function schemaSql(dialect) {
  const PK = dialect === 'pg'
    ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
    : 'INTEGER PRIMARY KEY AUTOINCREMENT';
  const BIG = dialect === 'pg' ? 'BIGINT' : 'INTEGER';
  const REAL = dialect === 'pg' ? 'DOUBLE PRECISION' : 'REAL';

  const pragmas = dialect === 'pg' ? '' : `
    PRAGMA journal_mode = WAL;
    PRAGMA foreign_keys = ON;
  `;

  return `${pragmas}
  CREATE TABLE IF NOT EXISTS brands (
    id    ${PK},
    name  TEXT NOT NULL UNIQUE,
    plan  TEXT DEFAULT 'Growth'
  );

  CREATE TABLE IF NOT EXISTS kocs (
    id        TEXT PRIMARY KEY,
    name      TEXT NOT NULL,
    username  TEXT,
    brand_id  ${BIG} REFERENCES brands(id)
  );

  CREATE TABLE IF NOT EXISTS sessions (
    id            ${PK},
    koc_id        TEXT NOT NULL REFERENCES kocs(id),
    brand_id      ${BIG} REFERENCES brands(id),
    dataset_id    ${BIG},
    started_at    TEXT,
    day           TEXT,
    hour          INTEGER,
    start_hm      TEXT,
    duration_min  ${REAL} DEFAULT 0,
    gmv           ${REAL} DEFAULT 0,
    gmv_live      ${REAL} DEFAULT 0,
    products_added INTEGER DEFAULT 0,
    distinct_sold INTEGER DEFAULT 0,
    orders        INTEGER DEFAULT 0,
    orders_live   INTEGER DEFAULT 0,
    items_sold    INTEGER DEFAULT 0,
    customers     INTEGER DEFAULT 0,
    avg_price     ${REAL} DEFAULT 0,
    cvr_session   ${REAL} DEFAULT 0,
    viewers       ${BIG} DEFAULT 0,
    views         ${BIG} DEFAULT 0,
    watch_avg_sec ${REAL} DEFAULT 0,
    comments      ${BIG} DEFAULT 0,
    shares        ${BIG} DEFAULT 0,
    likes         ${BIG} DEFAULT 0,
    new_followers ${BIG} DEFAULT 0,
    impressions   ${BIG} DEFAULT 0,
    clicks        ${BIG} DEFAULT 0,
    ctr           ${REAL} DEFAULT 0
  );

  CREATE INDEX IF NOT EXISTS idx_sessions_koc     ON sessions(koc_id);
  CREATE INDEX IF NOT EXISTS idx_sessions_day     ON sessions(day);
  CREATE INDEX IF NOT EXISTS idx_sessions_hour    ON sessions(hour);
  CREATE INDEX IF NOT EXISTS idx_sessions_brand   ON sessions(brand_id);
  CREATE INDEX IF NOT EXISTS idx_sessions_dataset ON sessions(dataset_id);

  CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS datasets (
    id          ${PK},
    label       TEXT,
    brand_id    ${BIG} REFERENCES brands(id),
    file_name   TEXT,
    sessions    INTEGER DEFAULT 0,
    date_from   TEXT,
    date_to     TEXT,
    created_at  TEXT
  );

  CREATE TABLE IF NOT EXISTS koc_stats (
    koc_id TEXT PRIMARY KEY REFERENCES kocs(id),
    sessions INTEGER, gmv ${REAL}, gmv_live ${REAL}, orders INTEGER, orders_live INTEGER,
    hours ${REAL}, viewers ${BIG}, views ${BIG}, impr ${BIG}, clicks ${BIG},
    comments ${BIG}, shares ${BIG}, likes ${BIG}, newfol ${BIG}, customers ${BIG},
    distinct_sold INTEGER, watch_avg ${REAL}, ctr ${REAL}, cvr ${REAL}, dtgio ${REAL}, aov ${REAL},
    score INTEGER, grade TEXT,
    comp_dtgio ${REAL}, comp_cvr ${REAL}, comp_ctr ${REAL}, comp_gmv ${REAL}, comp_reg ${REAL}
  );

  CREATE TABLE IF NOT EXISTS users (
    id            ${PK},
    username      TEXT NOT NULL UNIQUE,
    name          TEXT,
    role          TEXT DEFAULT 'viewer',
    pass_salt     TEXT NOT NULL,
    pass_hash     TEXT NOT NULL,
    created_at    TEXT
  );

  CREATE TABLE IF NOT EXISTS audit_log (
    id        ${PK},
    ts        TEXT,
    user_id   ${BIG},
    username  TEXT,
    action    TEXT,
    detail    TEXT
  );
  CREATE INDEX IF NOT EXISTS idx_audit_ts ON audit_log(id);
  `;
}

// Idempotent migrations for DBs created before a column existed.
export async function migrate(db) {
  if (db.dialect === 'pg') {
    await db.exec('ALTER TABLE sessions ADD COLUMN IF NOT EXISTS dataset_id BIGINT');
  } else {
    const cols = await db.all('PRAGMA table_info(sessions)');
    if (!cols.some((c) => c.name === 'dataset_id')) {
      await db.exec('ALTER TABLE sessions ADD COLUMN dataset_id INTEGER');
    }
  }
  await db.exec('CREATE INDEX IF NOT EXISTS idx_sessions_dataset ON sessions(dataset_id)');
}
